
package view;

import model.Fornecedor;
import service.FornecedorDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class TelaFornecedores extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaFornecedores.class.getName());

    private FornecedorDAO fornecedorDAO = new FornecedorDAO();
    /**
     * Creates new form TelaFornecedores
     */
    public TelaFornecedores() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        java.awt.Color escuro = new java.awt.Color(30, 30, 30);
        
        // 1. Pinta a janela principal
        this.getContentPane().setBackground(escuro);
        
        // 2. Pinta o jPanel1 (painel exterior)
        if (jPanel1 != null) {
            jPanel1.setBackground(escuro);
            jPanel1.setOpaque(true);
        }
        
        // 3. Pinta o jPanel2 (painel interior onde estão os botões e a tabela)
        if (jPanel2 != null) {
            jPanel2.setBackground(escuro);
            jPanel2.setOpaque(true);
        }
        
        // 4. Pinta o fundo da tabela e da barra de rolagem
        if (jScrollPane1 != null) {
            jScrollPane1.setBackground(escuro);
            jScrollPane1.getViewport().setBackground(escuro);
            jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        }
        
        // 5. Ajusta a cor do texto dos títulos para branco
        jLabel1.setForeground(java.awt.Color.WHITE);
        jLabel2.setForeground(java.awt.Color.WHITE);
    
carregarTabelaFornecedores();
    }

    public void carregarTabelaFornecedores() {
        DefaultTableModel modelo = (DefaultTableModel) tblFornecedores.getModel();
        modelo.setRowCount(0); // Limpa as linhas atuais

        List<Fornecedor> lista = fornecedorDAO.listarTodos();

        for (Fornecedor f : lista) {
            modelo.addRow(new Object[]{
                f.getId(),
                f.getRazaoSocial(),
                f.getCnpj(),
                f.getTelefone(),
                "✏️", // Coluna 4: Editar
            "🗑️"  // Coluna 5: Excluir
            });
        }
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnEstoque = new javax.swing.JButton();
        btnFornecedores = new javax.swing.JButton();
        btnVendas = new javax.swing.JButton();
        btnMenuPrincipal = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        btnNovoFornecedor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFornecedores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        btnEstoque.setText("Peças em estoque");
        btnEstoque.addActionListener(this::btnEstoqueActionPerformed);

        btnFornecedores.setText("Fornecedores");

        btnVendas.setText("Cadastro de vendas");
        btnVendas.addActionListener(this::btnVendasActionPerformed);

        btnMenuPrincipal.setText("Menu Principal");
        btnMenuPrincipal.addActionListener(this::btnMenuPrincipalActionPerformed);

        btnCompras.setText("Cadastro de compras ");
        btnCompras.addActionListener(this::btnComprasActionPerformed);

        btnSair.setBackground(new java.awt.Color(0, 0, 0));
        btnSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 51, 51));
        btnSair.setText("Sair");
        btnSair.addActionListener(this::btnSairActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Pesquisar");

        txtBusca.addActionListener(this::txtBuscaActionPerformed);

        btnNovoFornecedor.setBackground(new java.awt.Color(255, 0, 0));
        btnNovoFornecedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNovoFornecedor.setForeground(new java.awt.Color(0, 0, 0));
        btnNovoFornecedor.setText("+Novo Fornecedor");
        btnNovoFornecedor.addActionListener(this::btnNovoFornecedorActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Fornecedores");

        tblFornecedores.setBackground(new java.awt.Color(255, 255, 255));
        tblFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Razão Social", "CNPJ", "Telefone", "Editar", "Excluir"
            }
        ));
        tblFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFornecedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFornecedores);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel2)
                        .addGap(188, 188, 188)
                        .addComponent(btnNovoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnNovoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuPrincipal))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEstoque)
                        .addGap(18, 18, 18)
                        .addComponent(btnFornecedores)
                        .addGap(18, 18, 18)
                        .addComponent(btnCompras)
                        .addGap(18, 18, 18)
                        .addComponent(btnVendas)
                        .addGap(97, 97, 97)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(49, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menu = new MenuPrincipal();
    menu.setLocationRelativeTo(null);
    menu.setVisible(true);
    this.dispose(); // Fecha a tela atual
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
    login.setLocationRelativeTo(null);
    login.setVisible(true);
    this.dispose(); // Fecha a tela atual
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnNovoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoFornecedorActionPerformed
        // TODO add your handling code here:

     java.awt.Frame parentFrame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);

    FormFornecedorModal modal = new FormFornecedorModal(parentFrame, true);
    modal.setLocationRelativeTo(parentFrame);
    modal.setVisible(true);

    // Recarrega a tabela assim que o modal for fechado
    carregarTabelaFornecedores();
    }//GEN-LAST:event_btnNovoFornecedorActionPerformed

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
        String termo = txtBusca.getText().toLowerCase().trim();
    DefaultTableModel modelo = (DefaultTableModel) tblFornecedores.getModel();
    modelo.setRowCount(0);

    List<Fornecedor> lista = fornecedorDAO.listarTodos();

    for (Fornecedor f : lista) {
        if (f.getRazaoSocial().toLowerCase().contains(termo) || f.getCnpj().contains(termo)) {
            modelo.addRow(new Object[]{
                f.getId(),
                f.getRazaoSocial(),
                f.getCnpj(),
                f.getTelefone(),
               "✏️", // Coluna 4: Editar
            "🗑️"  // Coluna 5: Excluir
            });
        }
    }
    }//GEN-LAST:event_txtBuscaActionPerformed

    private void btnEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueActionPerformed
        // TODO add your handling code here:
        TelaEstoque estoque = new TelaEstoque();
    estoque.setLocationRelativeTo(null);
    estoque.setVisible(true);
    this.dispose(); // Fecha a tela atual
    }//GEN-LAST:event_btnEstoqueActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        // TODO add your handling code here:
        TelaCompras compras = new TelaCompras();
    compras.setLocationRelativeTo(null);
    compras.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasActionPerformed
        // TODO add your handling code here:
        TelaVendas vendas = new TelaVendas();
    vendas.setLocationRelativeTo(null);
    vendas.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnVendasActionPerformed

    private void tblFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFornecedoresMouseClicked
        // TODO add your handling code here:
       int linhaSelecionada = tblFornecedores.getSelectedRow();
    int colunaSelecionada = tblFornecedores.getSelectedColumn();

    if (linhaSelecionada == -1) {
        return;
    }

    int id = (int) tblFornecedores.getValueAt(linhaSelecionada, 0);

    // ✏️ AÇÃO DE EDITAR (Coluna 4)
    if (colunaSelecionada == 4) {
        // 1. Procura os dados completos do fornecedor selecionado
        Fornecedor fornecedorParaEditar = fornecedorDAO.buscarPorId(id);

        if (fornecedorParaEditar != null) {
            java.awt.Frame parentFrame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
            
            // 2. Abre o modal passando o fornecedor para preenchimento
            FormFornecedorModal modal = new FormFornecedorModal(parentFrame, true, fornecedorParaEditar);
            modal.setLocationRelativeTo(parentFrame);
            modal.setVisible(true);

            // 3. Recarrega a tabela após fechar a edição
            carregarTabelaFornecedores();
        }
    } 
    
    // 🗑️ AÇÃO DE EXCLUIR (Coluna 5)
    else if (colunaSelecionada == 5) {
        String razaoSocial = tblFornecedores.getValueAt(linhaSelecionada, 1).toString();

        int resposta = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente excluir o fornecedor: " + razaoSocial + "?",
            "Confirmar Exclusão",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE
        );

        if (resposta == javax.swing.JOptionPane.YES_OPTION) {
            boolean deletado = fornecedorDAO.excluir(id);

            if (deletado) {
                javax.swing.JOptionPane.showMessageDialog(this, "Fornecedor excluído com sucesso!");
                carregarTabelaFornecedores();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao excluir o fornecedor no banco de dados.");
            }
        }
    }

    }//GEN-LAST:event_tblFornecedoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaFornecedores().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnFornecedores;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JButton btnNovoFornecedor;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFornecedores;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
