
package view;

import model.Fornecedor;
import model.Peca;
import service.CompraDAO;
import service.FornecedorDAO;
import service.PecaDAO;
import java.util.List;


public class TelaCompras extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCompras.class.getName());

    /**
     * Creates new form TelaCompras
     */
    public TelaCompras() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        java.awt.Color fundoEscuro = new java.awt.Color(30, 30, 30);
        
        // 1. Pinta a janela principal
        this.getContentPane().setBackground(fundoEscuro);
        
        // 2. Pinta o jPanel1 e força a opacidade
        if (jPanel1 != null) {
            jPanel1.setBackground(fundoEscuro);
            jPanel1.setOpaque(true);
        }
        
        // 3. Ajusta o texto das caixas de entrada (texto preto sobre fundo branco)
        java.awt.Color textoEscuro = new java.awt.Color(0, 0, 0);
        txtQuantidade.setForeground(textoEscuro);
        txtCustoUnitario.setForeground(textoEscuro);
        txtBusca2.setForeground(textoEscuro);
    
    // 4. Carrega os dados do banco nos ComboBoxes
        carregarCombos();
    }

    private void carregarCombos() {
   // Carrega apenas os Fornecedores
    service.FornecedorDAO fornecedorDAO = new service.FornecedorDAO();
    java.util.List<model.Fornecedor> fornecedores = fornecedorDAO.listarTodos();
    cbFornecedor.removeAllItems();
    if (fornecedores != null) {
        for (model.Fornecedor f : fornecedores) {
            // Adiciona o ID e Nome do fornecedor na caixa de seleção
            cbFornecedor.addItem(f.getId() + " - " + f.getNome()); 
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBusca2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnEstoque = new javax.swing.JButton();
        btnFornecedores = new javax.swing.JButton();
        btnVendas = new javax.swing.JButton();
        btnMenuPrincipal = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrarCompra = new javax.swing.JButton();
        txtQuantidade = new javax.swing.JTextField();
        txtCustoUnitario = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbFornecedor = new javax.swing.JComboBox<>();
        txtSKU = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEstoque.setText("Peças em estoque");
        btnEstoque.addActionListener(this::btnEstoqueActionPerformed);

        btnFornecedores.setText("Fornecedores");
        btnFornecedores.addActionListener(this::btnFornecedoresActionPerformed);

        btnVendas.setText("Cadastro de vendas");
        btnVendas.addActionListener(this::btnVendasActionPerformed);

        btnMenuPrincipal.setText("Menu Principal");
        btnMenuPrincipal.addActionListener(this::btnMenuPrincipalActionPerformed);

        btnCompras.setText("Cadastro de compras ");

        btnSair.setBackground(new java.awt.Color(0, 0, 0));
        btnSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 51, 51));
        btnSair.setText("Sair");
        btnSair.addActionListener(this::btnSairActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Compras");

        btnRegistrarCompra.setBackground(new java.awt.Color(255, 0, 0));
        btnRegistrarCompra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarCompra.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarCompra.setText("Registrar Compra");
        btnRegistrarCompra.addActionListener(this::btnRegistrarCompraActionPerformed);

        txtQuantidade.setBackground(new java.awt.Color(255, 255, 255));

        txtCustoUnitario.setBackground(new java.awt.Color(255, 255, 255));
        txtCustoUnitario.addActionListener(this::txtCustoUnitarioActionPerformed);

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fornecedor");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SKU");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantidade");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Preço Unitário");

        cbFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        cbFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbFornecedor.addActionListener(this::cbFornecedorActionPerformed);

        txtSKU.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(79, 79, 79)
                .addComponent(btnRegistrarCompra)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCustoUnitario)
                    .addComponent(txtQuantidade)
                    .addComponent(cbFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSKU)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMenuPrincipal)
                    .addComponent(cbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnEstoque)
                        .addGap(18, 18, 18)
                        .addComponent(btnFornecedores)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSKU, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCompras)
                        .addGap(35, 35, 35)
                        .addComponent(btnVendas)
                        .addGap(97, 97, 97))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCustoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRegistrarCompra)
                        .addComponent(btnCancelar)))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menu = new MenuPrincipal();
    menu.setLocationRelativeTo(null);
    menu.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
    login.setLocationRelativeTo(null);
    login.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnRegistrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCompraActionPerformed
        // TODO add your handling code here:
 String itemFornecedor = (String) cbFornecedor.getSelectedItem();
String skuDigitado = txtSKU.getText().trim(); // Usa o campo de texto do SKU

if (itemFornecedor == null || skuDigitado.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Selecione um fornecedor e informe o SKU!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
    return;
}

if (txtQuantidade.getText().trim().isEmpty() || txtCustoUnitario.getText().trim().isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos da compra!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
    return;
}

try {
    int idFornecedor = Integer.parseInt(itemFornecedor.split(" - ")[0].trim());
    int quantidade = Integer.parseInt(txtQuantidade.getText().trim());
    double precoCusto = Double.parseDouble(txtCustoUnitario.getText().trim().replace(",", "."));

    service.PecaDAO pecaDAO = new service.PecaDAO();
    // Busca no banco se o SKU já existe
    model.Peca peca = pecaDAO.buscarPorSKU(skuDigitado);

    int idPeca;
    if (peca != null) {
        idPeca = peca.getId();
    } else {
        // Se não existir, você pode solicitar o nome para cadastrar na hora
        String nomeNovaPeca = javax.swing.JOptionPane.showInputDialog(this, "SKU não encontrado. Digite o nome da nova peça para cadastrá-la:");
        if (nomeNovaPeca == null || nomeNovaPeca.trim().isEmpty()) {
            return; // Cancela se não informar o nome
        }
        
        model.Peca novaPeca = new model.Peca();
        novaPeca.setSku(skuDigitado); // ou o campo correspondente no seu model
        novaPeca.setNome(nomeNovaPeca);
       
        idPeca = pecaDAO.cadastrar(novaPeca); // Retorna o ID gerado
    }

    // Registra a compra normalmente com o idFornecedor e idPeca
    service.CompraDAO dao = new service.CompraDAO();
    boolean sucesso = dao.registrarCompra(idPeca, idFornecedor, quantidade, precoCusto);

    if (sucesso) {
        javax.swing.JOptionPane.showMessageDialog(this, "Compra registrada e estoque atualizado com sucesso!", "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        txtSKU.setText("");
        txtQuantidade.setText("");
        txtCustoUnitario.setText("");
    }
} catch (NumberFormatException ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Valores numéricos inválidos!", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnRegistrarCompraActionPerformed
} 
    private void txtCustoUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustoUnitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustoUnitarioActionPerformed

    private void btnEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueActionPerformed
        // TODO add your handling code here:
        TelaEstoque estoque = new TelaEstoque();
    estoque.setLocationRelativeTo(null);
    estoque.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnEstoqueActionPerformed

    private void btnFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedoresActionPerformed
        // TODO add your handling code here:
        TelaFornecedores fornecedores = new TelaFornecedores();
    fornecedores.setLocationRelativeTo(null);
    fornecedores.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnFornecedoresActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        // Volta para o Menu Principal ou limpa os campos
    MenuPrincipal menu = new MenuPrincipal();
    menu.setLocationRelativeTo(null);
    menu.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasActionPerformed
        // TODO add your handling code here:
        TelaVendas vendas = new TelaVendas();
    vendas.setLocationRelativeTo(null);
    vendas.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnVendasActionPerformed

    private void cbFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCompras().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnFornecedores;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JButton btnRegistrarCompra;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVendas;
    private javax.swing.JComboBox<String> cbFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtBusca2;
    private javax.swing.JTextField txtCustoUnitario;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtSKU;
    // End of variables declaration//GEN-END:variables
}
