package view;

import javax.swing.table.DefaultTableModel;
import model.Peca;
import service.PecaDAO;
import java.util.List;

public class TelaEstoque extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEstoque.class.getName());
    
    // Instância da classe PecaDAO para acesso ao banco de dados
    private PecaDAO pecaDAO = new PecaDAO();

    /**
     * Creates new form TelaEstoque
     */
    public TelaEstoque() {
        initComponents();
        
        java.awt.Color fundoEscuro = new java.awt.Color(30, 30, 30);
        
        // 1. Pinta a janela principal
        this.getContentPane().setBackground(fundoEscuro);
        
        // 2. Pinta o jPanel1 e força a opacidade
        if (jPanel1 != null) {
            jPanel1.setBackground(fundoEscuro);
            jPanel1.setOpaque(true);
        }
        
        // 3. Ajusta o título para branco
        jLabel1.setForeground(java.awt.Color.WHITE);
        
        // 4. Mantém a tabela e o viewport em branco
        if (jScrollPane1 != null) {
            jScrollPane1.setBackground(java.awt.Color.WHITE);
            jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
        }
        
        // 5. Preenche os dados do estoque ao abrir a tela
        carregarTabelaEstoque();
    }

    // MÉTODO OFICIAL QUE CARREGA OS DADOS DO BANCO NA TABELA
    public void carregarTabelaEstoque() {
        DefaultTableModel model = (DefaultTableModel) tblEstoque.getModel();
        model.setRowCount(0);

        List<Peca> listaPecas = pecaDAO.listarTodas();

        for (Peca p : listaPecas) {
            model.addRow(new Object[]{
                p.getSku(),
                p.getNome(),
                p.getQuantidade(),
                p.getEstoqueMinimo(),
                String.format("R$ %.2f", p.getPrecoCusto()),
                String.format("R$ %.2f", p.getPrecoVenda()),
                "✏️  🗑️"
            });
        }
    }

    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEstoque = new javax.swing.JButton();
        btnFornecedores = new javax.swing.JButton();
        btnVendas = new javax.swing.JButton();
        btnMenuPrincipal = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstoque = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        btnEstoque.setText("Peças em estoque");

        btnFornecedores.setText("Fornecedores");
        btnFornecedores.addActionListener(this::btnFornecedoresActionPerformed);

        btnVendas.setText("Cadastro de vendas");
        btnVendas.addActionListener(this::btnVendasActionPerformed);

        btnMenuPrincipal.setText("Menu Principal");
        btnMenuPrincipal.addActionListener(this::btnMenuPrincipalActionPerformed);

        btnCompras.setText("Cadastro de compras ");
        btnCompras.addActionListener(this::btnComprasActionPerformed);

        btnSair.setBackground(new java.awt.Color(0, 0, 0));
        btnSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 51, 51));
        btnSair.setText("Sair");
        btnSair.addActionListener(this::btnSairActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Peças em estoque");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        tblEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "SKU", "Descrição", "QTD", "Min", "Custo", "Venda", "Ações"
            }
        ));
        tblEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEstoqueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEstoque);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnMenuPrincipal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEstoque)
                        .addGap(18, 18, 18)
                        .addComponent(btnFornecedores)
                        .addGap(18, 18, 18)
                        .addComponent(btnCompras)
                        .addGap(18, 18, 18)
                        .addComponent(btnVendas)
                        .addGap(97, 97, 97)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menu = new MenuPrincipal();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
     String termo = txtBusca.getText().trim().toLowerCase();
        DefaultTableModel model = (DefaultTableModel) tblEstoque.getModel();
        model.setRowCount(0);
        
        for (Peca p : pecaDAO.listarTodas()) {
            // Filtra por SKU ou Nome
            if (p.getSku().toLowerCase().contains(termo) || p.getNome().toLowerCase().contains(termo)) {
                model.addRow(new Object[]{
                    p.getSku(),
                    p.getNome(),
                    p.getQuantidade(),
                    p.getEstoqueMinimo(),
                    String.format("R$ %.2f", p.getPrecoCusto()),
                    String.format("R$ %.2f", p.getPrecoVenda()),
                    "✏️  🗑️"
                });
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedoresActionPerformed
        // TODO add your handling code here:
        TelaFornecedores fornecedores = new TelaFornecedores();
    fornecedores.setLocationRelativeTo(null);
    fornecedores.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnFornecedoresActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        // TODO add your handling code here:
        TelaCompras compras = new TelaCompras();
    compras.setLocationRelativeTo(null);
    compras.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasActionPerformed
        // TODO add your handling code here:
        TelaVendas vendas = new TelaVendas();
    vendas.setLocationRelativeTo(null);
    vendas.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnVendasActionPerformed

    private void tblEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEstoqueMouseClicked
        // TODO add your handling code here:
        int linhaSelecionada = tblEstoque.getSelectedRow();
    
    // Verifica se alguma linha foi realmente selecionada
    if (linhaSelecionada != -1) {
        // Pega a lista atual de peças para obter o ID correto da peça selecionada
        List<Peca> listaPecas = pecaDAO.listarTodas();
        Peca pecaSelecionada = listaPecas.get(linhaSelecionada);

        // Confirmação antes de eliminar
        int resposta = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente eliminar a peça: " + pecaSelecionada.getNome() + "?",
            "Confirmar Eliminação",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE
        );

        if (resposta == javax.swing.JOptionPane.YES_OPTION) {
            // Elimina no banco de dados usando o ID
            boolean eliminado = pecaDAO.excluir(pecaSelecionada.getId());

            if (eliminado) {
                javax.swing.JOptionPane.showMessageDialog(this, "Peça eliminada com sucesso!");
                carregarTabelaEstoque(); // Atualiza a tabela na tela
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao eliminar a peça no banco de dados.");
            }
        }
    }
    }//GEN-LAST:event_tblEstoqueMouseClicked
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaEstoque().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnFornecedores;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEstoque;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables

}