
package view;


public class TelaVendas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaVendas.class.getName());

    /**
     * Creates new form TelaVendas
     */
    public TelaVendas() {
        initComponents();
        this.setLocationRelativeTo(null); 
        java.awt.Color fundoEscuro = new java.awt.Color(30, 30, 30);
        
        // 1. Pinta a janela principal
        this.getContentPane().setBackground(fundoEscuro);
        
        // 2. Pinta o jPanel1 e força opacidade
        if (jPanel1 != null) {
            jPanel1.setBackground(fundoEscuro);
            jPanel1.setOpaque(true);
        }
        
        // 3. Ajusta o texto dos campos de entrada
        java.awt.Color textoEscuro = new java.awt.Color(0, 0, 0);
        txtCodigoVendaMl.setForeground(textoEscuro);
        txtSku.setForeground(textoEscuro);
        txtQuantidade.setForeground(textoEscuro);
        txtPrecoUnitario.setForeground(textoEscuro);
        txtValorTotal.setForeground(textoEscuro);

        // 4. Listener de digitação em tempo real (DENTRO do construtor)
        javax.swing.event.DocumentListener escutadorDeDigitacao = new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { calcularTotalAutomatico(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { calcularTotalAutomatico(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { calcularTotalAutomatico(); }
        };

        txtQuantidade.getDocument().addDocumentListener(escutadorDeDigitacao);
        txtPrecoUnitario.getDocument().addDocumentListener(escutadorDeDigitacao);
    } // <--- O CONSTRUTOR AGORA FECHA AQUI CORRETAMENTE!

    /**
     * Método auxiliar (FORA do construtor)
     */
    private void calcularTotalAutomatico() {
        String qtdTexto = txtQuantidade.getText().trim();
        String precoTexto = txtPrecoUnitario.getText().trim();

        if (!qtdTexto.isEmpty() && !precoTexto.isEmpty()) {
            try {
                int qtd = Integer.parseInt(qtdTexto);
                double preco = Double.parseDouble(precoTexto.replace(",", "."));
                double total = qtd * preco;
                txtValorTotal.setText(String.format("R$ %.2f", total));
            } catch (NumberFormatException e) {
                txtValorTotal.setText("R$ 0,00");
            }
        } else {
            txtValorTotal.setText("R$ 0,00");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEstoque = new javax.swing.JButton();
        btnFornecedores = new javax.swing.JButton();
        btnVendas = new javax.swing.JButton();
        btnMenuPrincipal = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrarVenda = new javax.swing.JButton();
        txtCodigoVendaMl = new javax.swing.JTextField();
        txtSku = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtValorTotal = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPrecoUnitario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        btnEstoque.setText("Peças em estoque");
        btnEstoque.addActionListener(this::btnEstoqueActionPerformed);

        btnFornecedores.setText("Fornecedores");
        btnFornecedores.addActionListener(this::btnFornecedoresActionPerformed);

        btnVendas.setText("Cadastro de vendas");

        btnMenuPrincipal.setText("Menu Principal");
        btnMenuPrincipal.addActionListener(this::btnMenuPrincipalActionPerformed);

        btnCompras.setText("Cadastro de compras ");
        btnCompras.addActionListener(this::btnComprasActionPerformed);

        btnSair.setBackground(new java.awt.Color(0, 0, 0));
        btnSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 51, 51));
        btnSair.setText("Sair");
        btnSair.addActionListener(this::btnSairActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Vendas");

        btnRegistrarVenda.setBackground(new java.awt.Color(255, 0, 0));
        btnRegistrarVenda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarVenda.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarVenda.setText("Registrar Venda");
        btnRegistrarVenda.addActionListener(this::btnRegistrarVendaActionPerformed);

        txtCodigoVendaMl.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoVendaMl.setForeground(new java.awt.Color(255, 255, 255));

        txtSku.setBackground(new java.awt.Color(255, 255, 255));
        txtSku.setForeground(new java.awt.Color(255, 255, 255));

        txtQuantidade.setBackground(new java.awt.Color(255, 255, 255));
        txtQuantidade.setForeground(new java.awt.Color(255, 255, 255));

        txtValorTotal.setEditable(false);
        txtValorTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtValorTotal.setForeground(new java.awt.Color(255, 255, 255));
        txtValorTotal.addActionListener(this::txtValorTotalActionPerformed);

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo de venda");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SKU da Peça");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantidade");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor Total da Venda");

        txtPrecoUnitario.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecoUnitario.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Preço Unitário");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(79, 79, 79)
                .addComponent(btnRegistrarVenda)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValorTotal)
                            .addComponent(txtSku)
                            .addComponent(txtCodigoVendaMl)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(20, 20, 20)))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoVendaMl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuPrincipal))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnEstoque)
                        .addGap(18, 18, 18)
                        .addComponent(btnFornecedores)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSku, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)))
                        .addGap(4, 4, 4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCompras)
                        .addGap(35, 35, 35)
                        .addComponent(btnVendas)
                        .addGap(97, 97, 97))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRegistrarVenda)
                        .addComponent(btnCancelar)))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueActionPerformed
        // TODO add your handling code here:
        TelaEstoque estoque = new TelaEstoque();
        estoque.setLocationRelativeTo(null);
        estoque.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEstoqueActionPerformed

    private void btnFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedoresActionPerformed
        // TODO add your handling code here:
        TelaFornecedores fornecedores = new TelaFornecedores();
        fornecedores.setLocationRelativeTo(null);
        fornecedores.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFornecedoresActionPerformed

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menu = new MenuPrincipal();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnRegistrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVendaActionPerformed
        // TODO add your handling code here:
     String skuDigitado = txtSku.getText().trim();
    String qtdTexto = txtQuantidade.getText().trim();
    String precoTexto = txtPrecoUnitario.getText().trim();

    // 1. Validação de campos vazios
    if (skuDigitado.isEmpty() || qtdTexto.isEmpty() || precoTexto.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, preencha o SKU, Quantidade e Preço Unitário!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        int quantidadeVenda = Integer.parseInt(qtdTexto);
        double precoVenda = Double.parseDouble(precoTexto.replace(",", "."));

        if (quantidadeVenda <= 0 || precoVenda < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "A quantidade deve ser maior que zero e o preço não pode ser negativo.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Busca a peça pelo SKU para verificar estoque
        service.PecaDAO pecaDAO = new service.PecaDAO();
        model.Peca peca = pecaDAO.buscarPorSKU(skuDigitado);

        if (peca == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Peça com o SKU '" + skuDigitado + "' não foi encontrada!", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Validação de Estoque Suficiente
        if (peca.getQuantidade() < quantidadeVenda) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Estoque insuficiente!\nEstoque atual: " + peca.getQuantidade() + " unidades.\nQuantidade solicitada: " + quantidadeVenda + " unidades.", 
                "Aviso de Estoque", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 4. Executa o registro da venda
        service.VendaDAO vendaDAO = new service.VendaDAO();
        boolean sucesso = vendaDAO.registrarVenda(peca.getId(), quantidadeVenda, precoVenda);

        if (sucesso) {
            double valorTotal = quantidadeVenda * precoVenda;
            
            // Exibe o total no campo txtValorTotal
            txtValorTotal.setText(String.format("R$ %.2f", valorTotal));

            javax.swing.JOptionPane.showMessageDialog(this, 
                "Venda registrada com sucesso!\nValor Total: R$ " + String.format("%.2f", valorTotal), 
                "Sucesso", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Limpa os campos
            txtSku.setText("");
            txtQuantidade.setText("");
            txtPrecoUnitario.setText("");
            txtCodigoVendaMl.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao registrar a venda no banco de dados.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Informe valores numéricos válidos para quantidade e preço!", "Erro de Validação", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnRegistrarVendaActionPerformed

    private void txtValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorTotalActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
     MenuPrincipal menu = new MenuPrincipal();
    menu.setLocationRelativeTo(null);
    menu.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        // TODO add your handling code here:
        TelaCompras compras = new TelaCompras();
    compras.setLocationRelativeTo(null);
    compras.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnComprasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaVendas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnFornecedores;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JButton btnRegistrarVenda;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCodigoVendaMl;
    private javax.swing.JTextField txtPrecoUnitario;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtSku;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
